### ISSUE TITLE
Submitting the registration form generates a csrf error

### ISSUE THREAD

**Issue by jonphipps** [evercode1/admin-dash#2]
In order to register an initial admin user, when I attempt to create the user through the user registration form, the site responds with a csrf token mismatch error. It looks like the session token is getting reset after the form is generated.

**Comment by evercode1** [comment]
That usually points to an environment problem.  Did you generate the app key?

**Comment by evercode1** [comment]
I had 'admin-test.com' listed as the domain in config/session.php, and this was obviously incorrect.  I have set it to null.  You will need to delete your cookie for the app from the browser and restart the browser to get it to work properly.  When you incorporate your facebook app, you will have to put your domain in session.php, and you will need to clear the cookie again to make it work properly.

**Comment by evercode1** [comment]
Your right, I will add that to the instructions because it will fire off an email with the registration event.

**Comment by evercode1** [comment]
.env example added to installation instructions.
