### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ucoker** [evercode1/admin-dash#3]
Hi，I use Homestead in Laravel.

Here is my steps:

- copy the `.env` to `admin-dash`
- run `composer install`
- run `php artisan key:generate`
- add the DB info
- run `php  artisan migrate`
- run `npm install`

After that, I open the `admin-dash` website, It show me `403 Forbidden`

How to solve it?

**Comment by evercode1** [comment]
I don't use homestead, so not sure on that one.  It sounds like an environment problem.  Here is a link to 403 errors explanation:  http://www.checkupdown.com/status/E403.html

**Comment by ucoker** [comment]
My mistake, the path of admin-dash was wrong in my Homestead configuration. It's worked.

**Comment by evercode1** [comment]
Thank you for updating.
